query_images: 'src/data/query_images_per_cpc_section.json'
query_dir: 'src/data/query_patents/sections/'
citations_data: 'src/data/query_patents/citations_data.json'

thresholds_dict: 'src/data/thresholds.json'

indices:
  title:
    dim: 1024
  desc:
    dim: 1024
  label:
    dim: 1024
  clip:
    dim: 1024
  patentnet:
    dim: 512
  resnext:
    dim: 2048

index_dir: 'src/indices'

cited_sample_size: 5

groups:
  positive:
    easy:
      text_percentile_range: ["100.000", "97.000"]
      image_percentile_range: ["100.000", "97.000"]
      size: 5
    hard:
      text_percentile_range: ["100.000", "97.000"]
      image_percentile_range: ["95.000", "92.000"]
      size: 5
  negative:
    easy:
      text_percentile_range: ["90.000", "87.000"]
      image_percentile_range: ["85.000", "82.000"]
      size: 80
    hard:
      text_percentile_range: ["90.000", "87.000"]
      image_percentile_range: ["100.000", "97.000"]
      size: 5

index:
  root_dir: '/path/to/dir'
  batch_size: 512
  num_workers: 8
  save_every: 512